
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pac-man-route
  namespace: pacman
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pacman-test.paxel.ca`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: pac-man
          port: 8080
---
# Service Definition for Pac-Man Application
apiVersion: v1
kind: Service
metadata:
  name: pac-man
  namespace: pacman
  labels:
    name: pac-man
  annotations:
    traefik.ingress.kubernetes.io/service-weight: "1"
    traefik.ingress.kubernetes.io/service-path: "/"
spec:
  selector:
    name: pac-man
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


---

# Deployment Definition for Pac-Man Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pac-man
  namespace: pacman
  labels:
    name: pac-man
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pac-man
  template:
    metadata:
      labels:
        name: pac-man
    spec:
      containers:
        - name: pac-man
          image: docker.io/jessehoch/pacman-nodejs-app:latest
          ports:
            - name: http-server
              containerPort: 8080
          env:
            - name: MONGO_SERVICE_HOST
              value: "mongo.pacman.svc.cluster.local"
            - name: MONGO_AUTH_USER
              value: "pacman"
            - name: MONGO_AUTH_PWD
              value: "pacman"
            - name: MONGO_DATABASE
              value: "pacman"
            # Additional environment variables can be added here as required
